# Configurações de UI/Interface
[ui]
theme = "dark"
logo_path = "/logos/customer-logo.png"
primary_color = "#3B82F6"
show_branding = true

# Configurações de Chat
[chat]
has_history = true
max_messages = 200
default_agent = "customer-assistant"
welcome_message = "Olá! Como posso ajudar você hoje?"
quick_replies = ["CH570", "CH670", "CH950", "A9000", "A8000", "A8810"]

# Recursos habilitados
[features]
agents = true
collections = true
teams = true
analytics = true

# Limites do plano
[limits]
max_users = 50
max_agents = 20
max_collections = 100
storage_mb = 10240  # 10GB

# Integrações permitidas
[integrations]
allowed_oauth = ["google", "microsoft", "github"]
webhook_url = "https://customer.example.com/webhook"

[integrations.api_keys]
openai = "sk-..."
anthropic = "sk-ant-..."